In [1]:
from lxml import etree
import re
html = etree.parse('http://doc.chacuo.net/iso-3166-1',etree.HTMLParser())
trs=html.xpath('//tr')
iso_eng = {}
iso_chn = {}
for tr in trs:
    iso3 = tr.xpath("td[2]/text()")
    iso3 = str(iso3)
    iso3 = iso3[2:-2]
    print("get %s"%iso3)
    eng_name = tr.xpath('td[5]/text()')
    eng_name = str(eng_name)
    eng_name = eng_name[2:-2]
    chn_name = tr.xpath('td[6]/text()')
    chn_name = str(chn_name)
    chn_name = chn_name[2:-2]
    iso_eng['%s'%eng_name]=iso3
    iso_chn['%s'%chn_name]=iso3

get
get AND
get ARE
get AFG
get ATG
get AIA
get ALB
get ARM
get AGO
get ATA
get ARG
get ASM
get AUT
get AUS
get ABW
get ALA
get AZE
get BIH
get BRB
get BGD
get BEL
get BFA
get BGR
get BHR
get BDI
get BEN
get BLM
get BMU
get BRN
get BOL
get BES
get BRA
get BHS
get BTN
get BVT
get BWA
get BLR
get BLZ
get CAN
get CCK
get CAF
get CHE
get CHL
get CMR
get COL
get CRI
get CUB
get CPV
get CXR
get CYP
get CZE
get DEU
get DJI
get DNK
get DMA
get DOM
get DZA
get ECU
get EST
get EGY
get ESH
get ERI
get ESP
get FIN
get FJI
get FLK
get FSM
get FRO
get FRA
get GAB
get GRD
get GEO
get GUF
get GHA
get GIB
get GRL
get GIN
get GLP
get GNQ
get GRC
get SGS
get GTM
get GUM
get GNB
get GUY
get HKG
get HMD
get HND
get HRV
get HTI
get HUN
get IDN
get IRL
get ISR
get IMN
get IND
get IOT
get IRQ
get IRN
get ISL
get ITA
get JEY
get JAM
get JOR
get JPN
get KHM
get KIR
get COM
get KWT
get CYM
get LBN
get LIE
get LKA
get LBR
get LSO
get LTU
get LUX
get LVA
get LBY
get MAR
get MCO
get MDA
get MNE
get MAF
get MDG
get MHL
get MKD
get MLI
get MMR
get MAC
get MTQ
get MRT
get MSR
get MLT
get MDV
get MWI
get MEX
get MYS
get NAM
get NER
get NFK
get NGA
get NIC
get NLD
get NOR
get NPL
get NRU
get OMN
get PAN
get PER
get PYF
get PNG
get PHL
get PAK
get POL
get PCN
get PRI
get PSE
get PLW
get PRY
get QAT
get REU
get ROU
get SRB
get RUS
get RWA
get SLB
get SYC
get SDN
get SWE
get SGP
get SVN
get SJM
get SVK
get SLE
get SMR
get SEN
get SOM
get SUR
get SSD
get STP
get SLV
get SYR
get SWZ
get TCA
get TCD
get TGO
get THA
get TKL
get TLS
get TUN
get TON
get TUR
get TUV
get TZA
get UKR
get UGA
get USA
get URY
get VAT
get VEN
get VGB
get VIR
get VNM
get WLF
get WSM
get YEM
get MYT
get ZAF
get ZMB
get ZWE
get CHN
get COG
get COD
get MOZ
get GGY
get GMB
get MNP
get ETH
get NCL
get VUT
get ATF
get NIU
get UMI
get COK
get GBR
get TTO
get VCT
get TWN
get NZL
get SAU
get LAO
get PRK
get KOR
get PRT
get KGZ
get KAZ
get TJK
get TKM
get UZB
get KNA
get SPM
get SHN
get LCA
get MUS
get CIV
get KEN
get MNG

In [5]:
import pandas as pd
eng_df = pd.DataFrame(list(iso_eng.items()), columns=['eng', 'iso3'])
chn_df = pd.DataFrame(list(iso_chn.items()), columns=['chn', 'iso3'])
eng_df = eng_df[1:]
chn_df = chn_df[1:]

In [7]:
eng_df.head()
chn_df.head()

                    eng iso3
1               Andorra  AND
2  United Arab Emirates  ARE
3           Afghanistan  AFG
4     Antigua & Barbuda  ATG
5              Anguilla  AIA

In [9]:
merge_df = pd.merge(chn_df,eng_df,on = "iso3")
merge_df.to_excel("iso国家代码.xls",index=False,encoding="utf-8")